# Generated by Django 5.2.17 on 2026-09-08 08:44

import django.db.models.deletion
import django.utils.timezone
import openwes.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0122_remove_purchaseorder_notes_remove_returnorder_notes_and_more'),
        ('part', '0154_remove_part_notes'),
        ('stock', '0128_remove_stockitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replenishment_id', models.CharField(db_index=True, default=openwes.models.generate_replenish_id, max_length=32, unique=True, verbose_name='Replenishment ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantity Required')),
                ('quantity_replenished', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15, verbose_name='Replenished Qty')),
                ('priority', models.IntegerField(default=30, verbose_name='Priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Operator'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('EXCEPTION', 'Blocked by Exception'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_replenishments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Operator')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks', to='part.part', verbose_name='Part')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_sources', to='stock.stocklocation', verbose_name='Reserve Source Location')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_targets', to='stock.stocklocation', verbose_name='Target Pick Face Location')),
            ],
            options={
                'verbose_name': 'Replenishment Task',
                'verbose_name_plural': 'Replenishment Tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Event UUID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, verbose_name='Client Idempotency Key')),
                ('device_id', models.CharField(blank=True, max_length=128, verbose_name='Device ID')),
                ('event_type', models.CharField(max_length=64, verbose_name='Event Type')),
                ('payload', models.JSONField(default=dict, verbose_name='Event Payload')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed Successfully'), ('CONFLICT', 'Conflict Detected'), ('REJECTED', 'Rejected / Validation Error')], default='RECEIVED', max_length=32, verbose_name='Sync Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Processing Error Message')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_sync_events', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Sync Event',
                'verbose_name_plural': 'Sync Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, default=openwes.models.generate_task_id, max_length=64, unique=True, verbose_name='Task ID')),
                ('task_type', models.CharField(choices=[('PICK', 'Pick Item'), ('PUTAWAY', 'Putaway Stock'), ('REPLENISH', 'Replenish Bin'), ('COUNT', 'Cycle Count'), ('RELOCATE', 'Relocate Stock')], db_index=True, default='PICK', max_length=32, verbose_name='Task Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Operator'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('EXCEPTION', 'Blocked by Exception'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32, verbose_name='Status')),
                ('priority', models.IntegerField(choices=[(10, 'Low Priority'), (20, 'Medium Priority'), (30, 'High Priority'), (40, 'Critical Priority')], db_index=True, default=20, verbose_name='Priority')),
                ('sequence', models.IntegerField(default=0, verbose_name='Route Sequence')),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=15, verbose_name='Expected Quantity')),
                ('picked_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=15, verbose_name='Picked Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Idempotency Key')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Operator')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_dest_tasks', to='stock.stocklocation', verbose_name='Destination Location')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_tasks', to='order.salesorder', verbose_name='Sales Order')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_tasks', to='order.salesorderlineitem', verbose_name='Order Line Item')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openwes_tasks', to='part.part', verbose_name='Part / SKU')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_source_tasks', to='stock.stocklocation', verbose_name='Source Location')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_tasks', to='stock.stockitem', verbose_name='Stock Item')),
            ],
            options={
                'verbose_name': 'Warehouse Task',
                'verbose_name_plural': 'Warehouse Tasks',
                'ordering': ['sequence', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_id', models.CharField(db_index=True, default=openwes.models.generate_exception_id, max_length=32, unique=True, verbose_name='Exception ID')),
                ('exception_type', models.CharField(choices=[('SHORT_PICK', 'Short Pick (Insufficient Stock)'), ('DAMAGED_ITEM', 'Damaged Item Found'), ('MISSING_ITEM', 'Missing Item in Bin'), ('BLOCKED_LOCATION', 'Blocked Location / Aisle'), ('WRONG_ITEM', 'Wrong Item / Barcode Mismatch'), ('WRONG_QUANTITY', 'Wrong Quantity Recorded'), ('STOCK_MISMATCH', 'System vs Physical Mismatch'), ('NETWORK_FAILURE', 'Network / Sync Failure')], db_index=True, default='SHORT_PICK', max_length=32, verbose_name='Exception Type')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened')], db_index=True, default='REPORTED', max_length=32, verbose_name='Ticket Status')),
                ('description', models.TextField(verbose_name='Problem Description')),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Expected Qty')),
                ('reported_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Reported Qty')),
                ('resolution', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_exceptions', to='stock.stocklocation', verbose_name='Location')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Reporting Operator')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_exceptions', to='part.part', verbose_name='Part')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By (Supervisor)')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='openwes.warehousetask', verbose_name='Warehouse Task')),
            ],
            options={
                'verbose_name': 'Warehouse Exception',
                'verbose_name_plural': 'Warehouse Exceptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STARTED', 'Task Started'), ('TASK_PAUSED', 'Task Paused'), ('TASK_RESUMED', 'Task Resumed'), ('ITEM_SCANNED', 'Item Barcode Scanned'), ('QUANTITY_CONFIRMED', 'Quantity Confirmed'), ('SHORT_PICK_REPORTED', 'Short Pick Reported'), ('ITEM_DAMAGED', 'Damaged Item Reported'), ('TASK_COMPLETED', 'Task Completed'), ('INVENTORY_ADJUSTED', 'Inventory Adjusted'), ('SYNC_COMPLETED', 'Offline Sync Completed'), ('REPLENISHMENT_GENERATED', 'Replenishment Task Generated'), ('EXCEPTION_REPORTED', 'Exception Reported'), ('EXCEPTION_RESOLVED', 'Exception Resolved')], db_index=True, max_length=64, verbose_name='Event Type')),
                ('summary', models.CharField(max_length=255, verbose_name='Event Summary')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Event Details')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor / User')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_audit_events', to='stock.stocklocation', verbose_name='Location')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_audit_events', to='part.part', verbose_name='Part')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='openwes.warehousetask', verbose_name='Warehouse Task')),
            ],
            options={
                'verbose_name': 'Warehouse Audit Event',
                'verbose_name_plural': 'Warehouse Audit Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Total Assignment Score')),
                ('distance_score', models.FloatField(default=0.0, verbose_name='Distance Score')),
                ('workload_score', models.FloatField(default=0.0, verbose_name='Workload Score')),
                ('priority_score', models.FloatField(default=0.0, verbose_name='Priority Score')),
                ('zone_score', models.FloatField(default=0.0, verbose_name='Zone Match Score')),
                ('reason', models.TextField(blank=True, verbose_name='Allocation Explanation / Reason')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openwes_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_detail', to='openwes.warehousetask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier e.g. ZONE-A, AISLE-1', max_length=32, unique=True, verbose_name='Zone Code')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('picking_strategy', models.CharField(choices=[('S_SHAPE', 'S-Shape / Snake Routing'), ('NEAREST_NEIGHBOR', 'Nearest-Neighbor TSP'), ('STRICT_ZONAL', 'Strict Zonal Ordering')], default='S_SHAPE', max_length=32, verbose_name='Default Picking Strategy')),
                ('priority', models.IntegerField(default=10, verbose_name='Priority')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openwes_zones', to='stock.stocklocation', verbose_name='Warehouse Location')),
            ],
            options={
                'verbose_name': 'Warehouse Zone',
                'verbose_name_plural': 'Warehouse Zones',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(blank=True, max_length=16, verbose_name='Aisle')),
                ('bay', models.CharField(blank=True, max_length=16, verbose_name='Bay / Rack')),
                ('level', models.CharField(blank=True, max_length=16, verbose_name='Shelf Level')),
                ('position', models.CharField(blank=True, max_length=16, verbose_name='Bin Position')),
                ('coord_x', models.FloatField(default=0.0, verbose_name='X Coordinate (Meters)')),
                ('coord_y', models.FloatField(default=0.0, verbose_name='Y Coordinate (Meters)')),
                ('coord_z', models.FloatField(default=0.0, verbose_name='Z Coordinate (Meters)')),
                ('is_pick_face', models.BooleanField(default=True, verbose_name='Is Pick Face')),
                ('is_reserve', models.BooleanField(default=False, verbose_name='Is Reserve Storage')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked')),
                ('block_reason', models.CharField(blank=True, max_length=255, verbose_name='Block Reason')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openwes_meta', to='stock.stocklocation', verbose_name='Stock Location')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='openwes.warehousezone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Warehouse Location Meta',
                'verbose_name_plural': 'Warehouse Location Metas',
            },
        ),
        migrations.CreateModel(
            name='OperatorSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128, verbose_name='Device / Terminal ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PICKING', 'Picking'), ('IDLE', 'Idle / Waiting'), ('BREAK', 'On Break'), ('BLOCKED', 'Blocked on Exception')], default='ONLINE', max_length=32, verbose_name='Current Status')),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Heartbeat')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='IP Address')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Battery %')),
                ('app_version', models.CharField(blank=True, max_length=32, verbose_name='App Version')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openwes_session', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_session', to='openwes.warehousetask', verbose_name='Active Task')),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_operators', to='openwes.warehousezone', verbose_name='Current Zone')),
            ],
            options={
                'verbose_name': 'Operator Session',
                'verbose_name_plural': 'Operator Sessions',
            },
        ),
    ]
